wikipedia: alias fix (#1912)
sopel-irc/sopel pull request #1966
Opened 2020-10-20 21:12 UTC by xnaas

2020-11-01 15:57 UTC, Exirel approved these changes
:100: agree.

2020-11-02 02:20 UTC, dgw commented
Since this is targeted for a major version bump… what if we were _really_ naughty and just nuked _all_ of the existing command names in favor of `.wikipedia` and `.wp`? Honestly, `.wiki` is a bit too generic—not as bad as `.w`, but still. 😜

I do have real reasoning behind this idea: Suppose someone wants to make a bot for some media franchise with a ton of very specific info available on a dedicated wiki (official or otherwise). Having `.wiki` available for use by plugins would let any fandom very easily make a bot that searches the de facto wiki for their niche, with an obvious command name that fits naturally.

2020-11-02 19:29 UTC, xnaas commented
I know this came up in IRC, but I'll comment it here as well.

I think the general consensus is that `wp` sounds like wordpress and `wiki` is pretty much automatically assumed as wikipedia, but ¯\\\_(ツ)_/¯ Obviously go with whatever you think is best. It's your bot, not mine. 😏

2021-06-06 14:02 UTC, dgw requested changes
Just formalizing what I said in a comment months ago.

2021-06-06 14:51 UTC, xnaas commented on sopel/modules/wikipedia.py
> +@plugin.example('.wiki San Francisco')
What about `wk` vs `wp`? 🤔 Similar to `wt`, I suppose.

2021-06-06 22:24 UTC, dgw commented on sopel/modules/wikipedia.py
> +@plugin.example('.wiki San Francisco')
WaniKani? 😂

Jokes aside, `.wk` could be an abbreviation for just about _any_ Wikimedia project. They all have those two letters in the first three letters of the project name.

Wiktionary is a special case, really. Just about everything else follows the "Wikisomething" pattern, with both i's in the "wiki" part:

- Wikipedia
- Wikiquote
- Wikibooks
- Wikisource
- Wikispecies
- Wikinews
- Wikiversity
- Wikivoyage
- Wikidata

Ignoring the overlaps there (`ws` and `wv` could each represent two projects), the obvious abbreviation for each is `w_`, where the second character is what comes after the "Wiki" part.

I don't understand the resistance to using `wp`. 😕 The Wikipedia project itself uses that abbreviation as an internal shortcut—policy pages in the `Wikipedia:` namespace have short names like `WP:MOS`.

2021-06-06 22:29 UTC, RustyBower commented
I agree. I think we should avoid single character commands as much as possible, there's too much opportunity for collision

2021-06-06 23:31 UTC, xnaas commented on sopel/modules/wikipedia.py
> +@plugin.example('.wiki San Francisco')
> I don't understand the resistance to using `wp`. 😕

Personally-motivated greed. 😜 — decade of habit/comfort. It's fine, though. Can always route my own `wk` command do it or something.

2021-06-08 05:32 UTC, dgw approved these changes
History cleaned. Didn't expect @xnaas of all people to be one of those Vigilant Mode nerds 😜 so feel free to `--amend` the commit here with a proper signature.

2021-06-30 03:41 UTC, merged