plugin: keep old-school plugin devs happy w/plural command decorators
sopel-irc/sopel pull request #1967
Opened 2020-10-20 21:34 UTC by dgw

### Description
Enough people expressed dismay that our upcoming migration to `sopel.plugin` (from `sopel.module`) would get rid of the plural `commands` decorator family. So we can have both, and plugin devs may choose depending on how they decorate stuff.

```py
@plugin.command('justone')
def one_name(bot, trigger):
    pass

@plugin.commands('multiple', 'names')
def two_names(bot, trigger):
    pass
```

I gave the aliases very short docstrings that just link back to the main entry, so Sphinx wouldn't duplicate the whole shebang.

@Exirel, is adding tests for the aliases worthwhile? I don't feel like bothering. 😝

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [x] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [x] I have tested the functionality of the things this change touches

2020-10-21 08:14 UTC, Exirel requested changes
You need to update `sopel.module`'s imports as well.

2020-10-21 22:32 UTC, dgw commented
@Exirel Wait, so now you're _in favor_ of touching deprecated stuffs? 😼

2020-10-22 03:52 UTC, Exirel commented
@dgw your PR is about un-deprecating `commands`, tho.

2020-10-22 04:09 UTC, dgw commented
@Exirel `plugin.commands` wasn't deprecated; it never existed (except briefly in an unreleased state, between #1898 and #1924, for about a month). It's just, after the little row we had over touching deprecated code in #1944, I was surprised that you _wanted_ me to do so here. It makes sense. Importing with `as` is silly if not needed. Just didn't expect it.

2020-10-22 04:15 UTC, Exirel approved these changes

2020-12-14 23:42 UTC, merged