quality: Docstring formatting
sopel-irc/sopel pull request #1978
Opened 2020-10-31 22:41 UTC by half-duplex

### Description
Adds flake8-docstrings and starts cleanup for putting it in use.

First commit is only requirements, config, spacing changes, raw strings for backslashes, and punctuation. No new or meaningfully changed docstrings.

Second adds minor rephrases and reformats, like "Gets xyz" → "Get xyz".

Third adds restructures and rephrases. A couple are check-dodging ("Home directory for...") but I [disagree with D401 on properties](https://github.com/PyCQA/pydocstyle/issues/301) anyway

Relates to #1765

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [x] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [x] I have tested the functionality of the things this change touches

2020-10-31 23:37 UTC, half-duplex commented
To tl;dr IRC:
- D401's heuristics and its enforcement on properties are somewhat annoying, though slightly improved in v3+
- Exirel does the most with docs and doesn't want "[this tool that] enforces only compliance, not quality"

2020-11-01 11:29 UTC, Exirel requested changes
First round of review. I still think it's too early to add a strong docstring check, and I still think these little changes don't actually improve the documentation.

2020-11-01 11:29 UTC, Exirel commented on sopel/config/__init__.py
> +        """Home directory for config file.
Ditto @ "property are not method from the reader pov".

2020-11-01 11:29 UTC, Exirel commented on sopel/irc/backends.py
> +        """Handle active opener's new accepted connection."""
Lost details here.

2020-11-01 11:29 UTC, Exirel commented on sopel/loader.py
> +    """Clean the callable. (compile regexes, fix docs, set defaults).
Is it proper grammar?

2020-11-01 11:29 UTC, Exirel commented on sopel/modules/admin.py
> +    Can only be done in privmsg by an admin.
While we are at it, let's remove the possible confusion between `PRIVMSG` and "Private message":

```suggestion
    Can only be done in a private message by an admin.
```

2020-11-01 11:29 UTC, Exirel commented on sopel/modules/admin.py
> +    Can only be done in privmsg by an admin.
Same:

```suggestion
    Can only be done in a private message by an admin.
```

2020-11-01 11:29 UTC, Exirel commented on sopel/modules/admin.py
> +    """Monitor KICK messages to rejoin if kicked.
```suggestion
    """Monitor ``KICK`` messages to rejoin if kicked.
```

2020-11-01 11:29 UTC, Exirel commented on sopel/modules/admin.py
> +    """Send an ACTION (/me) to a given channel or nick.
```suggestion
    """Send an ``ACTION`` (``/me``) to a given channel or nick.
```

2020-11-01 11:29 UTC, Exirel commented on sopel/modules/adminchannel.py
> +    """Op users in a room.
Maybe we should change `room` to `channel`?

2020-11-01 11:29 UTC, Exirel commented on sopel/modules/adminchannel.py
> +    """Op users in a room.
```suggestion
    """Op users in a channel.
```

2020-11-01 11:29 UTC, Exirel commented on sopel/modules/adminchannel.py
> +    """Deop users in a room.
```suggestion
    """Deop users in a channel.
```

2020-11-01 11:29 UTC, Exirel commented on sopel/modules/adminchannel.py
> +    """Voice users in a room.
```suggestion
    """Voice users in a channel.
```

2020-11-01 11:29 UTC, Exirel commented on sopel/modules/adminchannel.py
> +    """Devoice users in a room.
```suggestion
    """Devoice users in a channel.
```

2021-12-23 16:52 UTC, dgw commented
Could revisit this now that most of the stuff to be removed in 8.0 is gone. Even so, I think we're best off with a transitional period where this check is a separate `make` target so it can report any violations in this category without failing the build (as described in https://github.com/PyCQA/flake8/issues/515#issuecomment-812812944). We can keep an eye on the status as our PRs churn and _maybe_ decide to enforce it later.

There are so many merge conflicts now that it's probably easier to add the plugin and apply fixes from scratch. Since I literally asked to use this in #1765, I'm certainly happy to be the one who goes over everything again. (Could be therapeutic after all my end-of-year stuff is done at work.)

2022-02-24 14:47 UTC, dgw commented
We're still going to do this, but in a much less invasive way. The sane approach is to first start getting in the habit of linting everything we touch with the new rules and fixing any style violations. We can slowly work our way up to hardline enforcement at the `make quality` step in CI. But more importantly, we can avoid having one monolithic PR that tries to touch everything.

2022-02-24 14:47 UTC, closed without merging