irc: test sopel.irc.utils.safe function
sopel-irc/sopel pull request #1983
Opened 2020-11-06 22:43 UTC by Exirel

### Description

`sopel.irc.utils.safe` wasn't tested, now it is. Also with a better docstring.

### Checklist

- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [x] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [x] I have tested the functionality of the things this change touches

2020-11-08 00:09 UTC, dgw requested changes
Looks straightforward enough, but it seems like something was copied and pasted that needs updating. 😁

2020-11-08 00:09 UTC, dgw commented on test/irc/test_irc_utils.py
> +"""Tests for core ``sopel.irc.isupport``"""
`isupport`? What?

2020-11-08 08:54 UTC, Exirel commented on test/irc/test_irc_utils.py
> +"""Tests for core ``sopel.irc.isupport``"""
lol

2020-11-09 09:03 UTC, Exirel commented on test/irc/test_irc_utils.py
> +"""Tests for core ``sopel.irc.isupport``"""
Should be good now.

2020-12-25 22:38 UTC, dgw approved these changes
Imagine asking for a one-line change and then forgetting about the PR for 6 weeks… 🙊

2020-12-27 21:40 UTC, merged