url: urlban/unban commands
sopel-irc/sopel pull request #2028
Opened 2021-02-06 14:33 UTC by Exirel

### Description

Close #1870

And because nothing is simple: I also added aliases for `urlpban` and `urlpunban` to ban/unban patterns instead of URL directly.

### Checklist

- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [x] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [x] I have tested the functionality of the things this change touches

2021-02-06 16:19 UTC, cottongin commented
I like this, my only suggestion is what do you think about renaming the commands to use a different word than "ban"?

At least to me using "ban" implies banning someone from using the plugin. I know it also includes "url" in the command name, so perhaps it is less confusing to others, but the plugin is also named `url.py`... (maybe a better suggestion would be to rename the plugin `title.py` or something)

2021-02-06 16:21 UTC, Exirel commented
If you have something better than `ban`, I'll take it. `urlexclude` maybe?

2021-02-06 16:25 UTC, cottongin commented
Yes sure, exclude makes more sense to me

2021-02-23 20:10 UTC, dgw requested changes
"urlpunban" lol 😹

I couldn't take the time just now to think about the `# re-compile` steps, but surely there's a way to manage `bot.memory['url_exclude']` without running a whole list comprehension every time?

2021-02-23 20:10 UTC, dgw commented on sopel/modules/url.py
> +    patterns = bot.settings.url.exclude or []
No need to fall back on an empty list; `ListAttribute` already presents as empty list if not set.

```suggestion
    patterns = bot.settings.url.exclude
```

2021-02-23 20:10 UTC, dgw commented on sopel/modules/url.py
> +    bot.settings.url.exclude = patterns
Not necessary if `patterns` is a simple assignment to `bot.config.url.exclude`; it'll be the same object reference.

```suggestion
```

2021-02-23 20:10 UTC, dgw commented on sopel/modules/url.py
> +    patterns = bot.settings.url.exclude or []
See comments/suggestions in `url_ban()` above.

```suggestion
    patterns = bot.settings.url.exclude
```

2021-02-23 20:10 UTC, dgw commented on sopel/modules/url.py
> +    bot.settings.url.exclude = patterns
See `url_ban()` comments.

```suggestion
```

2021-02-25 06:40 UTC, Exirel commented
> I couldn't take the time just now to think about the `# re-compile` steps, but surely there's a way to manage `bot.memory['url_exclude']` without running a whole list comprehension every time?

I think there is, but I couldn't bother to do something complicated without the proper unit-test to back me up. I think the tradeoff is good for now. I know I tend to be a bit lazy with tests when it comes to plugin, because I never know if I really want to invest in them right now, or wait for when they are all external plugins. After all, I did a 100% test coverage on sopel-help, and I'm doing that for remind too...

2021-02-25 06:44 UTC, dgw submitted a review, later dismissed
Squash at will, sir. 🖖

2021-02-25 07:36 UTC, Exirel commented
OK, I squashed and rebased after some further fix and changes, making it worthy of a second full review, I think.

I've settled for `urlexclude` and `urlallow` in hope of making @cottongin happy. We discussed this with @dgw but neither of us had an opinion about it. We decided to keep the `url(pun)ban` because it's funny.

2021-02-28 20:56 UTC, dgw approved these changes
Retitled to reflect the extra fix Exi sneakily added, so I remember to mention it in the changelog.

2021-03-21 07:33 UTC, merged