Adds 2-word pronouns aliases to pronoun module
sopel-irc/sopel pull request #2069
Opened 2021-05-17 21:13 UTC by eliocamp

### Description

Adds 2-word common pronoun sets. 

Closes #2068 

I didn't check it on my machine because it feels trivial. Let me know if you want me to test it properly. 

### Checklist
- [ ] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [ x ] I can and do license this contribution under the EFLv2
- [ ] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [ ] I have tested the functionality of the things this change touches

2021-05-17 21:20 UTC, Exirel requested changes
All good for me. The small nitpick is just a convention thing. For the merge commit, we'll see with @dgw how to squash that.

2021-05-17 21:20 UTC, Exirel commented on sopel/modules/pronouns.py
> +    'ey/em': 'ey/em/eir/eirs/eirslef'
Nitpick: it's a convention to keep the last trailing comma:

```suggestion
    'ey/em': 'ey/em/eir/eirs/eirslef',
```

2021-05-17 21:25 UTC, Exirel approved these changes

2021-05-17 23:05 UTC, dgw reviewed
@Exirel I'd just rebase the branch to fixup the commit messages. However, though I haven't had a chance to look at it yet, it seems #2070 will supersede this.

2021-05-17 23:05 UTC, dgw commented on sopel/modules/pronouns.py
> +    'ey/em': 'ey/em/eir/eirs/eirslef',
L35 has been wrong for who knows how long. L36 copied the mistake.


```suggestion
    'ey': 'ey/em/eir/eirs/eirself',
    'ey/em': 'ey/em/eir/eirs/eirself',
```

2021-05-24 02:27 UTC, dgw approved these changes
I'll massage the commit history a bit, but it's basically ready to 🚢.

2021-05-24 05:26 UTC, merged