docs: be even more specific that `owner` is ALWAYS required
sopel-irc/sopel pull request #2112
Opened 2021-06-20 05:04 UTC by dgw

### Description
Noticed that while the docstring for `core_section.CoreSection.owner` specifies that it's always required, the "Owners & Admins" docs chapter didn't say anything about it, which could lead users to be confused.

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [x] No issues are reported by `make qa` (runs `make quality` and `make test`)
  - Doesn't touch any `.py` files, so I didn't run those.
- [x] I have tested the functionality of the things this change touches
  - N/A, like the above

### Notes
Don't know yet if we'll need a 7.1.2 release, but I'm sure it'll happen. This is the first PR for it, apparently.

2021-06-20 09:46 UTC, Exirel commented
Hm. I really don't like that. I mean, for 7.1.2 I'm fine, it's fixing a problem where we can fix it without breaking change.

However, I don't like forcing owner to set a config value that is ignored, it feels a bit weird. I'll see if I can think of something for Sopel 8.

2021-06-20 09:51 UTC, Exirel requested changes

2021-06-20 09:51 UTC, Exirel commented on docs/source/configuration.rst
> +    owner = DoesNotMatter
```suggestion
    owner = dgw
```

I'd not let people put a "wrong" owner name, they might trip on that latter. You know how people work: they don't. They are broken and they make the most infuriating errors all the times. Let's not help them doing more harm.

Even tho I totally get the "DoesNotMatter". 😁

2021-06-20 09:51 UTC, Exirel commented on docs/source/configuration.rst
> +be ignored (but ``owner`` **must** still have a value).
Maybe we should add a `.. note:` or `.. important:` here?

2021-06-21 00:33 UTC, dgw commented
> I don't like forcing owner to set a config value that is ignored, it feels a bit weird.

Hard agree. I'm sure you already know this was never intended to be the final word, just a clarification for our stable branch.

To that end, you might like what I did with the `.. important::` block. Push incoming; rendered preview below.

![image](https://user-images.githubusercontent.com/164140/122693175-4f768d80-d1fe-11eb-8443-be6b30559cca.png)

2021-06-21 07:38 UTC, Exirel approved these changes
Squash away!

2021-06-28 05:05 UTC, merged