pronouns: fetch list from the pronoun.is GitHub repo at start
sopel-irc/sopel pull request #2130
Opened 2021-06-30 21:44 UTC by dgw

### Description
We don't have to wait until the 12th of Never for pronoun.is to have an API. Parsing tab-separated values is easy, and the file is already sorted according to approximate frequency for us according to their readme.

Includes a kill-switch config setting in case the repo ever gets deleted or reorganized, or the file format changes.

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [x] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [x] I have tested the functionality of the things this change touches

### Notes
Speaking of something that's over-complicated for what it does (as Exi said on IRC yesterday)… this also finds the shortest unique set of pronouns for each option to use in links. The only outlier cases now are `they/them/their/theirs/themsel(ves|f)`, which won't be abbreviated as `they/.../themsel(ves|f)`. I might or might not find the motivation to fix that.

2021-10-30 22:19 UTC, Exirel requested changes
I don't really get the tree aspect of the pronoun parsing. I feel like I'm missing the problem that required a solution.

I also tried to run the code on the current pronoun file, and the result is quite different from the default set of pronouns. For example, instead of `'they/.../themselves'`, the parser returns `'they/them/their/theirs/themselves'`. So, is it compatible? Why use `...` in the default value, knowing that the actual file don't contain them? Especially given that the file will replace the default value, so if there is a feature here, it'll be made inaccessible.

A lot of confusion!

2021-10-30 22:19 UTC, Exirel commented on sopel/modules/pronouns.py
> +    def get_pairs(self, root=None, prefix=''):
I think I hate the complexity of this method.

2021-10-30 22:19 UTC, Exirel commented on sopel/modules/pronouns.py
> +                len(split_request) == 3
I don't really understand the change in names here. Sure, I don't really like "known_pronoun_set", I'd just use "known_pronouns".

2021-10-30 22:19 UTC, Exirel commented on sopel/modules/pronouns.py
> +                len(split_request) == 3
And yeah, both "split_request" and "request_pronoun_split" tries to encode too much information in one name. I'd just go with "requested_pronoun". 🤷

2022-02-24 03:01 UTC, dgw commented
> I don't really get the tree aspect of the pronoun parsing. I feel like I'm missing the problem that required a solution.

Using a trie was to make it easier to match on prefixes. I think. It's been a few months. 😅

I've <em>trie</em>d (😏) to address most of the style comments in fixup commits. Haven't gone through another round of testing just yet.

2022-04-27 05:58 UTC, Exirel approved these changes
I still think this is a lot of work that I don't know how to justify. On the other hand, I didn't have to do anything, and it all looks good. Maybe I'm just annoyed there isn't any test for that yet, but there wasn't before anyway.

Let's move on.

2022-05-10 17:51 UTC, dgw commented
I have cleaned the history (squashing fixups) and fixed one last bug with the disambiguation output (in case the user specifies e.g. `.setpronouns they`, which matches multiple sets).

Testing also determined that it's not necessary to merge the fetched pronouns with the default set; `they/.../themself` (for example) works just fine without that entry existing in the dictionary. I dropped that change.

2022-05-10 18:08 UTC, merged