tools.time: handle aware datetimes too in `format_time()`
sopel-irc/sopel pull request #2132
Opened 2021-07-02 07:07 UTC by dgw

### Description
As a side note, the absolute fallback default time format has been changed here to use `%z` (UTC offset) instead of `%Z` (zone name), since the zone name is almost never useful and the offset is actually handy to have in tests. And in the output, too...

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [x] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [x] I have tested the functionality of the things this change touches

### Notes
After faffing around _way_ too much with the tests, I'm not _entirely_ sure any more if their passing actually means anything. Sure, `tools.time.format_time()` seems to do what I expect in an interactive console, but… that's not a unit test.

I don't _think_ this warrants "Breaking Change" treatment since the only user-facing behavior change is the output when _no_ other time format source is passed to `format_time()` and it uses the tweaked default… but opinions may vary. Maybe aware `datetime` objects being legal now should be called out.

2021-07-05 05:53 UTC, Exirel requested changes

2021-07-05 05:53 UTC, Exirel commented on test/tools/test_tools_time.py
> +            tzinfo=UTC,
It looks very UTC to me.

2021-07-05 06:01 UTC, Exirel approved these changes
Alright, it's getting better.

2021-07-19 21:07 UTC, dgw commented
Note for my future self: Labeled as Breaking Change after all, just to mention the new default in changelog.

2021-07-19 21:07 UTC, merged