Revert "bot: deprecate `search_url_callbacks()` method"
sopel-irc/sopel pull request #2156
Opened 2021-07-12 14:26 UTC by RhinosF1

This reverts commit 3986227c4971e68530ae07113426187e95967046.

```
 <+Exirel> 
Because Sopel still uses `search_url_callbacks`, and have to.
14:01:55 <RhinosF1> 
it does
14:02:21 <+Exirel> 
Yup. So yeah, we need to find a better solution than that.
14:04:19 <RhinosF1> 
I can hack beta if anything needs testing
14:07:20 <+Exirel> 
I think we should not trigger a warning on `search_url_callbacks` in 8.0, make it a no-op in 9.0, and remove it in 10.0.
```

### Description
Revert 3986227c4971e68530ae07113426187e95967046.

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [x] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [x] I have tested the functionality of the things this change touches

2021-07-12 14:29 UTC, Exirel requested changes

2021-07-12 14:29 UTC, Exirel commented on sopel/bot.py
> -        .. deprecated:: 8.0
Not that part! The documentation should stay in place. 😄

2021-07-12 14:30 UTC, RhinosF1 commented
> Notice: /Stage[main]/Sopel::Dev/Exec[rebuild sopel]: Triggered 'refresh' from 1 event
Deployed

2021-07-12 15:13 UTC, Exirel commented
For the record:

```
15:07:38 <+Exirel> Or just remove it.
15:08:42 <+Exirel> Because after all, it is useful only if you use the other methods, and those are not used by Sopel anymore and they are marked as deprecated.
15:08:48 <+Exirel> So I think that's enough warning.
15:09:02 <+Exirel> Beside, the deprecation note in the doc should be enough.
15:09:07 <+Exirel> No need to spam logs with that deprecation warning.
```

2021-07-12 15:13 UTC, Exirel approved these changes

2021-07-12 17:06 UTC, dgw commented
Why not use a `warning_in='9.0'` kwarg to `@deprecated`, plus a TODO comment? There should be a TODO anyway as a reminder to no-op this function in 9.0.

2021-07-18 05:07 UTC, merged

2021-07-18 05:08 UTC, dgw commented
N.B.: I elected not to worry about this spitting out a warning once the version hits 9.0-dev. Bikeshedding ain't worth it.