seen: modify calculation to work now that `trigger.time` is Aware
sopel-irc/sopel pull request #2265
Opened 2022-03-07 06:20 UTC by dgw

### Description
Fixes a bug on `master` reported on IRC by monaco (@hedho), related to `trigger.time` changes from #2099.

I chose to eliminate the bug by using Unix timestamps instead of `datetime` objects. `<datetime_obj>.timestamp()` [has been around since Python 3.3](https://docs.python.org/3.9/library/datetime.html#datetime.datetime.timestamp), so we're safe to use it with 8.x's minimum requirement of Python 3.7.

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [x] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [x] I have tested the functionality of the things this change touches

2022-03-07 09:15 UTC, Exirel requested changes
I think it would be best to add this change (line 68):

```diff
- bot.db.set_nick_value(nick, 'seen_timestamp', time.time())
+ bot.db.set_nick_value(nick, 'seen_timestamp', trigger.time.timestamp())
```

2022-03-07 21:47 UTC, Exirel commented
Yeah, but it's a good opportunity to be more coherent with the feature. `trigger.time` is timezone sensitive, and I feel like it makes more sense to use it here as well. Beside, if the event comes from the IRC history (if that ever get implemented), we won't have to update the `seen` plugin (at least, not that part).

2022-03-07 21:59 UTC, dgw commented
> `trigger.time` is timezone sensitive

Well, this is annoying, but not because of what you said. It's annoying that `time.time()` isn't always in UTC.

Give me a moment to update the patch.

2022-04-27 06:12 UTC, Exirel approved these changes

2022-05-05 05:03 UTC, merged