implement flake8-type-checking
sopel-irc/sopel pull request #2300
Opened 2022-06-08 19:14 UTC by half-duplex

### Description
Tin. See #1765

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [?] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [x] I have tested the functionality of the things this change touches

2022-06-08 23:25 UTC, half-duplex commented
Had to restrict it to python 3.8+ since flake8-type-checking doesn't support 3.7...

2022-06-09 00:45 UTC, dgw commented
Think I threw it on the todo pile in #1765 instead of just doing it immediately _because_ there's no support for 3.7… But there's actually nothing that breaks if someone runs style checks on 3.7, only the potential for missing TC error codes that CI will flag. And probably no one should be running their main development on anything older than 3.8 or 3.9… so I declare my past self silly.

Can you exclude/ignore the TC200 error series? We want to use delayed evaluation (it's why our files use `from __future__ import annotations`), not forward references. Might also want `type-checking-exempt-modules = typing`, which would make the places where `from typing` appears _both_ inside and outside the `TYPE_CHECKING` block unnecessary.

(My present self is also silly, just for different reasons.)

2022-06-29 19:14 UTC, dgw commented
Cool. Time to ask for review from the one with actual experience using mypy.

2022-06-30 08:32 UTC, Exirel commented
That's interesting. Maybe it's also time to officially add `mypy` to the mix then?

2022-07-03 18:39 UTC, dgw commented
Could be, if it doesn't generate any errors after merging with `master`. Whatcha think about this otherwise?

2022-07-10 13:51 UTC, Exirel approved these changes
I'm OK with that as long as ` make mypy` works.

2022-07-14 12:36 UTC, Exirel requested changes

2022-07-14 18:33 UTC, half-duplex commented on setup.cfg
> +    TC2,  # We use postponed annotation evaluation
Fixed

2022-07-17 10:35 UTC, Exirel approved these changes

2022-07-17 12:16 UTC, merged