reqs: allow xmltodict 0.13
sopel-irc/sopel pull request #2334
Opened 2022-07-27 00:11 UTC by dgw

### Description
Tin. I tried and tried, but couldn't find any reason not to allow the newer version of xmltodict now that we no longer support Python 2.

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [x] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [x] I have tested the functionality of the things this change touches

### Notes
On IRC, @Strykar said this _does_ break something, but I have no idea what (no details). I invite them to post said details here.

2022-07-27 00:13 UTC, dgw commented
… Coveralls is broken again. Really? 😑

2022-07-27 02:36 UTC, Strykar commented
> ### Notes
> 
> On IRC, @Strykar said this _does_ break something, but I have no idea what (no details). I invite them to post said details here.

Unsure how much this will help, but disabling tests fixes the issue:
```
$ namcap PKGBUILD 
$ makepkg -s
==> Making package: sopel 7.1.9-1 (Tue 26 Jul 2022 07:29:08 PM IST)
==> Checking runtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...

Packages (6) python-maxminddb-2.2.0-4  python-prawcore-2.3.0-3  python-update-checker-0.18.0-5  python-geoip2-4.5.0-1  python-praw-7.6.0-1  python-xmltodict-0.13.0-2

Total Download Size:   0.34 MiB
Total Installed Size:  2.55 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 python-maxminddb-2.2.0-4-x86_64                                                                                               26.0 KiB  4.55 KiB/s 00:06 [###############################################################################################] 100%
 python-prawcore-2.3.0-3-any                                                                                                   27.2 KiB  4.75 KiB/s 00:06 [###############################################################################################] 100%
 python-update-checker-0.18.0-5-any                                                                                            13.1 KiB  2.28 KiB/s 00:06 [###############################################################################################] 100%
 python-geoip2-4.5.0-1-any                                                                                                     32.1 KiB  5.39 KiB/s 00:06 [###############################################################################################] 100%
 python-praw-7.6.0-1-any                                                                                                      238.9 KiB  38.9 KiB/s 00:06 [###############################################################################################] 100%
 python-xmltodict-0.13.0-2-any                                                                                                 15.8 KiB  2.57 KiB/s 00:06 [###############################################################################################] 100%
 Total (6/6)                                                                                                                  353.1 KiB  54.7 KiB/s 00:06 [###############################################################################################] 100%
(6/6) checking keys in keyring                                                                                                                            [###############################################################################################] 100%
(6/6) checking package integrity                                                                                                                          [###############################################################################################] 100%
(6/6) loading package files                                                                                                                               [###############################################################################################] 100%
(6/6) checking for file conflicts                                                                                                                         [###############################################################################################] 100%
(6/6) checking available disk space                                                                                                                       [###############################################################################################] 100%
:: Running pre-transaction hooks...
(1/1) Checking Arch News with Informant ...
There are no unread news items
:: Processing package changes...
(1/6) installing python-xmltodict                                                                                                                         [###############################################################################################] 100%
(2/6) installing python-prawcore                                                                                                                          [###############################################################################################] 100%
(3/6) installing python-update-checker                                                                                                                    [###############################################################################################] 100%
(4/6) installing python-praw                                                                                                                              [###############################################################################################] 100%
(5/6) installing python-maxminddb                                                                                                                         [###############################################################################################] 100%
(6/6) installing python-geoip2                                                                                                                            [###############################################################################################] 100%
:: Running post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Searching for orphaned packages...
python-geoip2 4.5.0-1
python-praw 7.6.0-1
python-xmltodict 0.13.0-2
(3/3) Syncing file system on /...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...

Packages (8) python-apipkg-2.1.1-1  python-iniconfig-1.1.1-5  python-pluggy-1.0.0-1  python-py-1.11.0-1  python-pytest-7.1.2-1  python-pytest-runner-5.3.2-1  python-requests-mock-1.9.3-3  python-sphinxcontrib-autoprogram-0.1.7-3

Total Download Size:   0.75 MiB
Total Installed Size:  3.69 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 python-apipkg-2.1.1-1-any                                                                                                     12.4 KiB  15.8 KiB/s 00:01 [###############################################################################################] 100%
 python-iniconfig-1.1.1-5-any                                                                                                   9.0 KiB  11.0 KiB/s 00:01 [###############################################################################################] 100%
 python-requests-mock-1.9.3-3-any                                                                                              30.9 KiB  36.9 KiB/s 00:01 [###############################################################################################] 100%
 python-pluggy-1.0.0-1-any                                                                                                     25.4 KiB  29.7 KiB/s 00:01 [###############################################################################################] 100%
 python-sphinxcontrib-autoprogram-0.1.7-3-any                                                                                  16.9 KiB  18.6 KiB/s 00:01 [###############################################################################################] 100%
 python-pytest-runner-5.3.2-1-any                                                                                              12.1 KiB  11.6 KiB/s 00:01 [###############################################################################################] 100%
 python-pytest-7.1.2-1-any                                                                                                    500.3 KiB   396 KiB/s 00:01 [############################################################ [...]

2022-07-27 16:40 UTC, dgw commented
Hm, the errors in that log look like what happened the last time I tried to run tests in pytest 7, without upgrading xmltodict. I don't think that breakage is related to this specific upgrade.

2022-07-29 20:54 UTC, dgw commented
Damn it, I did the misclick thing again. Anyway, I vote to delay this (my own PR, yes) until after #2328.

No, I don't know why the tests that were passing now fail flake8. I didn't touch those, but something must have updated upstream.

2022-08-13 06:47 UTC, dgw commented
OK, same change but on top of `pyproject.toml` after merging #2328.

2022-08-13 07:38 UTC, Exirel requested changes
Minor change requested. Once fixed you can directly go to merge in my opinion, as tests pass.

2022-08-13 07:38 UTC, Exirel commented on pyproject.toml
> +    "xmltodict<0.14",
This seems more appropriate to me: it allows 0.13, and requires at least 0.12, so someone wouldn't accidentally install a lower version than it was previously possible.

```suggestion
    "xmltodict>=0.12,<0.14",
```

2022-08-16 14:40 UTC, Exirel approved these changes

2022-08-17 01:05 UTC, merged