docs: add example of plugin re-use
sopel-irc/sopel pull request #2489
Opened 2023-07-12 01:59 UTC by SnoopJ

### Description

This changeset adds an example to the "tips and tricks" for plugins of importing another plugin and re-using a command from therein, as well as a warning about the potential for the duplication problem described in #2488.

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [N/A] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [x] I have tested the functionality of the things this change touches

2023-07-12 02:28 UTC, dgw reviewed
These are just style nits. Bigger thing is that you can import a plugin's module even if it's not loaded, so the example could also be used to "rename" a preexisting command.

2023-07-12 02:28 UTC, dgw commented on docs/source/plugin/advanced.rst
> +.. warning::
```suggestion
.. warning::

```

2023-07-12 02:28 UTC, dgw commented on docs/source/plugin/advanced.rst
> +    module rather than unpacking callables from it using a 'from' import.
```suggestion
    module rather than unpacking its callables using a ``from`` import.
```

2023-07-13 09:33 UTC, Exirel requested changes
I'd approve this, however I think there is at least one note to be added: we should say that the single-file plugin type may not work this way, because it may not be importable. You can link to single-file plugin definition with:

```rst
Link to :term:`Single file plugin` definition.
```

2023-07-13 09:33 UTC, Exirel commented on docs/source/plugin/advanced.rst
> +    defined in the current plugin. This can lead to duplication of plugin
```suggestion
    exposed in the current plugin. This can lead to duplication of plugin
```

2023-07-14 03:49 UTC, SnoopJ commented
> we should say that the single-file plugin type may not work this way, because it may not be importable

I'd love to see information of this sort added to Sopel, but I think it's a deeper subject than the warning I wanted to add in this case. I figure that users who are importing not-a-builtin-plugin are probably going to find out about the distinction anyway, and I'm not really sure how to expand this section to tackler the larger subject of how one might go about locating and importing plugins.

Do you think it makes sense to file a separate issue for fleshing out the subject?

2023-07-14 08:05 UTC, Exirel commented
It's an advanced tips & tricks section, we can direct the reader to more resources without having to explain everything. Beside, there is an explanation about [single-file plugin already](https://sopel.chat/docs/plugin/what.html#id3). I don't think it's that deeper that it requires another issue: a single line in this section is enough in my opinion.

2023-07-15 14:24 UTC, Exirel approved these changes
🚢

2023-07-16 19:27 UTC, dgw approved these changes
:shipit: (but squash first, please)

2023-07-16 21:55 UTC, merged