docs: add docstring to library root module
sopel-irc/sopel pull request #2494
Opened 2023-07-15 02:56 UTC by SnoopJ

### Description
This PR fixes #2493 by adding a module-level docstring to `sopel/__init__.py`. I just copied the first two sentences from https://sopel.chat

### Checklist
- [x] I have read [CONTRIBUTING.md](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md)
- [x] I can and do license this contribution under the EFLv2
- [N/A] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [N/A] I have tested the functionality of the things this change touches

2023-07-15 03:37 UTC, SnoopJ commented
And actually, digging further into this, the issue is no longer actually present after Python 3.7, when [PEP 538](https://peps.python.org/pep-0538/) was implemented to coerce the C locale to UTF-8. I believe we could remove the restriction to use only ASCII text in that module, and the [associated warning](https://github.com/sopel-irc/sopel/blob/c26914b68913bc25bdd1f5fed9c5942a87fdfee6/sopel/__init__.py#L38-L43) might be superfluous now as well.

I'll leave that out of this PR unless y'all agree that they can go, but the default behavior since 3.7 is to coerce these problematic locales to UTF-8, so the problem just doesn't exist in versions we support now anyway.

2023-07-15 08:48 UTC, Exirel requested changes
Let's remove the rant now. 😁

2023-07-16 01:25 UTC, SnoopJ commented
Done. I preserved the warning about non-UTF-8 locale but softened the language of it a bit. I'm not really sure it's a concern anymore with the changes that happened since Python 3.7, but I'm not confident enough to remove it entirely for the handful of users who will have a locale that is not using UTF-8 and is not coerced to same.

2023-07-16 10:24 UTC, Exirel approved these changes

2023-07-17 22:50 UTC, dgw approved these changes
Sure, why not. (I dismissed the CodeQL alert about running `print()` at the module level. This is "something's seriously screwed up in the environment" code, so I think we can leave it be.)

2023-07-19 20:07 UTC, merged